### ISSUE TITLE
Respond 400 Bad Request when params in request URI or body can't be decoded, not just closing the connection

### ISSUE THREAD

**Issue by ungit** [xitrum-framework/xitrum#508]
Reproduce:
download xitrum-new, run project
send request: curl "http://localhost:8000/?test=%s"
In console: 
> [WARN] Could not parse query params URI: /?test=%test
java.lang.IllegalArgumentException: invalid escape sequence `%te' at index 0 of: %test
	at io.netty.handler.codec.http.QueryStringDecoder.decodeComponent(QueryStringDecoder.java:352) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.http.QueryStringDecoder.decodeParams(QueryStringDecoder.java:252) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.http.QueryStringDecoder.parameters(QueryStringDecoder.java:204) ~[netty-all-4.0.25.Final.jar:4.0.25.Final]
	at xitrum.handler.inbound.UriParser.channelRead0(UriParser.scala:32) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.UriParser.channelRead0(UriParser.scala:16) [xitrum_2.11-3.22.jar:3.22]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at xitrum.handler.inbound.WebJarsServer.channelRead0(WebJarsServer.scala:33) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.WebJarsServer.channelRead0(WebJarsServer.scala:23) [xitrum_2.11-3.22.jar:3.22]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at xitrum.handler.inbound.PublicFileServer.channelRead0(PublicFileServer.scala:33) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.PublicFileServer.channelRead0(PublicFileServer.scala:23) [xitrum_2.11-3.22.jar:3.22]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at xitrum.handler.inbound.BaseUrlRemover.channelRead0(BaseUrlRemover.scala:23) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.BaseUrlRemover.channelRead0(BaseUrlRemover.scala:11) [xitrum_2.11-3.22.jar:3.22]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at xitrum.handler.inbound.Request2Env.sendUpstream(Request2Env.scala:290) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.Request2Env.channelRead0(Request2Env.scala:101) [xitrum_2.11-3.22.jar:3.22]
	at xitrum.handler.inbound.Request2Env.channelRead0(Request2Env.scala:49) [xitrum_2.11-3.22.jar:3.22]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:182) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:130) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137) [netty-all-4.0.25.Final.jar:4.0.25.Final]
	at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]

but no response 400 Bad Request

**Comment by ngocdaothanh** [comment]
When the server side can't parse the request, currently, the behavior is to close the connection without responding anything:
https://github.com/xitrum-framework/xitrum/blob/master/src/main/scala/xitrum/handler/inbound/UriParser.scala#L38

This is intentional: If attackers send garbage to the server, the server just closes the connection. It doesn't bother wasting CPU cycles to respond 400 Bad Request.

I think 400 Bad Request is for logical errors at app level (not HTTP request parsing level), like when you expect a positive number, but the client sends you a negative number.

In this issue, the request itself is grammatically wrong, so I think the current behavior is reasonable.

**Comment by ungit** [comment]
Our company provide restful api, and some users sends query but forgot to encode it. This queries is invalid, but users can`t understand why connection is dropped. We want to respond nice page to user with good explanation. For example, we can configure nginx to track for 400 response code and show a nice page. It is possible to override default behaviour in someway?

**Comment by georgeOsdDev** [comment]
You can add your own custom netty handler and channelInitializer with xitrum.Server.
http://xitrum-framework.github.io/api/3.22/#xitrum.Server$

Default handlers and ChannelInitializer is defined here.
https://github.com/xitrum-framework/xitrum/blob/master/src/main/scala/xitrum/handler/DefaultHttpChannelInitializer.scala

And in your handler, override [`exceptionCaught`](http://netty.io/4.0/api/io/netty/channel/ChannelInboundHandlerAdapter.html) method.
http://netty.io/wiki/user-guide-for-4.x.html#wiki-h3-6

Xitrum's default exceptionCaught is  `BadClientSilencer`
https://github.com/xitrum-framework/xitrum/blob/46f330ac6c360688417406dcc1539ebb8704b721/src/main/scala/xitrum/handler/inbound/BadClientSilencer.scala

**Comment by ungit** [comment]
Thanks.

**Comment by ngocdaothanh** [comment]
As georgeOsdDev described, Xitrum Guide has an advanced chapter that describes how to override handlers in the request (and response) processing pipeline:
http://xitrum-framework.github.io/guide/3.22/html/en/handler.html

You can do like this:

Create MyUriParser that you need, based on Xitrum's [UriParser](https://github.com/xitrum-framework/xitrum/blob/master/src/main/scala/xitrum/handler/inbound/UriParser.scala).

Then create MyHttpChannelInitializer that replaces Xitrum's UriParser with yours:

```scala
class MyHttpChannelInitializer extends xitrum.handler.DefaultHttpChannelInitializer {
  private myUriParser = new MyUriParser

  override def initChannel(ch: SocketChannel) {
    super.initChannel(ch)
    val p = ch.pipeline
    p.replace(classOf[UriParser], "myUriParser", myUriParser)
  }
}
```

Lastly, when starting Xitrum web server, tell it to use MyHttpChannelInitializer:

```scala
xitrum.Server.start(new MyHttpChannelInitializer)
```

Your use case is reasonable. In the next Xitrum version, we'll respond a tiny response to tell clients that they are sending bad requests.

**Comment by caiiiycuk** [comment]
There are another significant problem. We use nginx as frontend proxy with node balancer. Our config looks like: 
```sh
   upstream api {
        least_conn;
        server 10.0.0.24:8510 fail_timeout=5s max_fails=3;
        server 10.0.0.26:8510 fail_timeout=5s max_fails=3;
        server 10.0.0.34:8510 backup;
   }
```

Nginx decides that upstream is down if upstream drop connection (without responding status code). 
```
[error] 104412#0: *958052049 upstream prematurely closed connection while reading response header from upstream, client: ...
```

So if three clients send broken request, than all our nodes will be blacklisted and our api going down.

**Comment by ngocdaothanh** [comment]
Thanks for pointing that out. We'll include your comment in the source code of the next version of UriParser.

**Comment by georgeOsdDev** [comment]
@ngocdaothanh 
I made patch brunch in my fork. But I have some questions about Exceptions caught at BadClientSilencer. Which exception should respond status code 400 and which should close channel without respond status code.

**Comment by ngocdaothanh** [comment]
@georgeOsdDev 

I think you shouldn't modify BadClientSilencer (throwing exception from UriParser and catch it at BadClientSilencer). Instead, just simply respond 400 Bad Request right at UriParser.

There are several reasons:
* Throwing exception is [costly](https://www.google.co.jp/search?q=java+throwing+exception+cost), while we want to minimize cost for bad clients.
* BadClientSilencer is for catching uncaught exceptions, i.e. exceptions that haven't been caught by other handlers in the pipeline, while the exception has already been caught by UriParser.

**Comment by georgeOsdDev** [comment]
@ngocdaothanh 
Thanks, I fixed code and created PR #510 .

**Comment by ngocdaothanh** [comment]
@georgeOsdDev 
Similarly, please also send 400 Bad Request when the request body can't be parsed. Search for "channel.close()" in this handler:
https://github.com/xitrum-framework/xitrum/blob/3f9b6f9c9c6412694fc565077de7d10df8af4706/src/main/scala/xitrum/handler/inbound/Request2Env.scala

**Comment by ngocdaothanh** [comment]
@ungit and @caiiiycuk:
In the laster source code, we close the connection after sending Bad Request 400.
Is that OK?
Do we have to leave the connection open after sending Bad Request 400?

**Comment by caiiiycuk** [comment]
It is ok. I think we should close connection on bad request. Thanks

**Comment by caiiiycuk** [comment]
Also i think it will be better to  print cause here:
```scala
if (msg.getDecoderResult.isFailure) {
      ctx.channel.close()
      BadClientSilencer.respond400(ctx.channel, "Server could not decode request, cause: " + msg.getDecoderResult.cause().getMessage)
      return
```

**Comment by ngocdaothanh** [comment]
OK, I'll add the info.

**Comment by ngocdaothanh** [comment]
@caiiiycuk I've pushed the change. Thanks for the comment.
