### ISSUE TITLE
routes.cache should be saved in tmpDir as configured in xitrum.conf

### ISSUE THREAD

**Issue by ungit** [xitrum-framework/xitrum#541]
Reproduce: 
1. Download xitrum-new 
2. remove "tmpDir = ./tmp" in config/xitrum.conf
3. sbt run

**Comment by ngocdaothanh** [comment]
What operating system are you using?

I've just tested on Mac.
Xitrum starts OK.
There's no error.

When you remove or comment out "tmpDir = ./tmp" in config/xitrum.conf, Xitrum will use a random directory in the system directory. It will log the directory path when it starts, like this:

```
[INFO] Xitrum tmpDir: /var/folders/gc/14jrc47n1k17cz4zfx2f9t6h0000gp/T/xitrum-1052052536966139562-tmp
[INFO] Load tmp/routes.cache or recollect routes...
```

Because the directory is random, when you stop and start again, the directory will change, like this:

```
[INFO] Xitrum tmpDir: /var/folders/gc/14jrc47n1k17cz4zfx2f9t6h0000gp/T/xitrum-6628034328879212600-tmp
[INFO] Load tmp/routes.cache or recollect routes...
```

**Comment by ungit** [comment]
OS openSUSE.
```
[INFO] Slf4jLogger started
[INFO] Xitrum tmpDir: /tmp/xitrum-5125399136864612276-tmp
[INFO] Load tmp/routes.cache or recollect routes...
[INFO] Could not load tmp/routes.cache, delete and retry...
[INFO] Load tmp/routes.cache or recollect routes...
[ERROR] Could not collect routes
java.io.FileNotFoundException: tmp/routes.cache (Нет такого файла или каталога)
	at java.io.FileOutputStream.open(Native Method) ~[na:1.7.0_40]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:221) ~[na:1.7.0_40]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171) ~[na:1.7.0_40]
	at sclasner.Scanner$.doFoldLeftAndSerialize(Scanner.scala:72) ~[sclasner_2.11-1.6.jar:1.6]
	at sclasner.Scanner$.deserializeCacheFileWithFallback(Scanner.scala:46) ~[sclasner_2.11-1.6.jar:1.6]
	at sclasner.Scanner$.foldLeft(Scanner.scala:20) ~[sclasner_2.11-1.6.jar:1.6]
	at xitrum.routing.RouteCollector$.deserializeCacheFileOrRecollect(RouteCollector.scala:40) ~[xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Config$.loadRouteCacheFileOrRecollectWithRetry(Config.scala:406) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Config$.loadRouteCacheFileOrRecollectWithRetry(Config.scala:425) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Config$.loadRoutes(Config.scala:398) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Config$.<init>(Config.scala:394) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Config$.<clinit>(Config.scala) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Server$.start(Server.scala:42) [xitrum_2.11-3.24.0.jar:3.24.0]
	at xitrum.Server$.start(Server.scala:33) [xitrum_2.11-3.24.0.jar:3.24.0]
	at quickstart.Boot$.main(Boot.scala:7) [classes/:na]
	at quickstart.Boot.main(Boot.scala) [classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_40]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_40]
	at sbt.Run.invokeMain(Run.scala:67) [run-0.13.8.jar:0.13.8]
	at sbt.Run.run0(Run.scala:61) [run-0.13.8.jar:0.13.8]
	at sbt.Run.sbt$Run$$execute$1(Run.scala:51) [run-0.13.8.jar:0.13.8]
	at sbt.Run$$anonfun$run$1.apply$mcV$sp(Run.scala:55) [run-0.13.8.jar:0.13.8]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55) [run-0.13.8.jar:0.13.8]
	at sbt.Run$$anonfun$run$1.apply(Run.scala:55) [run-0.13.8.jar:0.13.8]
	at sbt.Logger$$anon$4.apply(Logger.scala:85) [logging-0.13.8.jar:0.13.8]
	at sbt.TrapExit$App.run(TrapExit.scala:248) [run-0.13.8.jar:0.13.8]
	at java.lang.Thread.run(Thread.java:724) [na:1.7.0_40]
```
'mkdir tmp' in xitrum-new directory fixes this problem

**Comment by ngocdaothanh** [comment]
Thanks for the info.
I'll try to reproduce and fix the problem.

**Comment by ngocdaothanh** [comment]
@ungit Andrey, Thanks for the bug report. Currently routes.cache is always saved in tmp subdirectory of the current directory. I've fixed it.
