### ISSUE TITLE
autosetLanguage throws java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by georgeOsdDev** [xitrum-framework/xitrum#664]
Specific 'Accept-Language'  like 'nv' cause 500 Error.

See:
https://bugs.openjdk.java.net/browse/JDK-8135061

Reproduce code

```
@GET("")
class SiteIndex extends DefaultLayout {
  beforeFilter {
    autosetLanguage("ja", "en")
  }
  def execute() {
    respondView()
  }
}
```

```
$ curl -LI 'http://localhost:8000' -H 'Accept-Language:en' -o /dev/null -w '%{http_code}\n' -s
200

$ curl -LI 'http://localhost:8000' -H 'Accept-Language:ja' -o /dev/null -w '%{http_code}\n' -s
200

$ curl -LI 'http://localhost:8000' -H 'Accept-Language:fr' -o /dev/null -w '%{http_code}\n' -s
200

$ curl -LI 'http://localhost:8000' -H 'Accept-Language:nv' -o /dev/null -w '%{http_code}\n' -s
500

$ curl -LI 'http://localhost:8000' -H 'Accept-Language:xxx' -o /dev/null -w '%{http_code}\n' -s
200
```

```
[INFO] Xitrum 3.28.9 started in development mode

[ERROR] Dispatch error 0:0:0:0:0:0:0:1 HEAD / -> quickstart.action.SiteIndex -> 500, 7 [ms]
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1954)
	at sun.util.locale.LocaleMatcher.lookupTag(LocaleMatcher.java:233)
	at java.util.Locale.lookupTag(Locale.java:3280)
	at xitrum.I18n.autosetLanguage(I18n.scala:63)
	at xitrum.I18n.autosetLanguage$(I18n.scala:62)
	at quickstart.action.SiteIndex.autosetLanguage(SiteIndex.scala:6)
	at quickstart.action.SiteIndex.$anonfun$new$1(SiteIndex.scala:8)
	at quickstart.action.SiteIndex$$Lambda$2174/1076397294.apply$mcV$sp(Unknown Source)
```

**Comment by ngocdaothanh** [comment]
It's interesting that the response code is 200 for `xxx`, but 500 for `nv`.

**Comment by ngocdaothanh** [comment]
We can reproduce the problem with Scala REPL:

```
scala> java.util.Locale.lookupTag(java.util.Locale.LanguageRange.parse("xxx"), java.util.Arrays.asList("en", "ja"))
res1: String = null
```

```
scala> java.util.Locale.lookupTag(java.util.Locale.LanguageRange.parse("nv"), java.util.Arrays.asList("en", "ja"))
java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.substring(String.java:1967)
  at sun.util.locale.LocaleMatcher.lookupTag(LocaleMatcher.java:233)
  at java.util.Locale.lookupTag(Locale.java:3280)
  ... 29 elided
```

**Comment by ngocdaothanh** [comment]
I think the only solution is to add `try catch`. What do you think?

**Comment by ngocdaothanh** [comment]
Oh it's a JDK bug reported a long time ago:
https://bugs.openjdk.java.net/browse/JDK-8135061

**Comment by georgeOsdDev** [comment]
Yes this exception not occur with java10 (maybe java9).
`try catch` is most simple solution For java8 user

**Comment by ngocdaothanh** [comment]
I've added `try catch`.

I'll release a new version very soon, after updating dependencies.

**Comment by georgeOsdDev** [comment]
👍
